import type { PreguntaEstudio } from "../tipos";
import { bancoPreguntasExtra } from "./preguntasExtra";

export const bancoPreguntas: Record<string, PreguntaEstudio[]> = {
  "1": [
    {
      id: "1-q1",
      idTema: "1",
      enunciado: "¿Cuál es la función principal del corazón?",
      tipo: "opcion-multiple",
      dificultad: "facil",
      opciones: [
        { id: "a", etiqueta: "Producir hormonas" },
        { id: "b", etiqueta: "Bombear sangre" },
        { id: "c", etiqueta: "Filtrar la sangre" },
        { id: "d", etiqueta: "Producir oxígeno" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "El corazón funciona como una bomba muscular que impulsa la sangre a través de los vasos sanguíneos mediante contracciones rítmicas.",
    },
    {
      id: "1-q2",
      idTema: "1",
      enunciado: "¿Qué cavidad del corazón bombea sangre oxigenada hacia todo el cuerpo?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "Aurícula derecha" },
        { id: "b", etiqueta: "Ventrículo derecho" },
        { id: "c", etiqueta: "Aurícula izquierda" },
        { id: "d", etiqueta: "Ventrículo izquierdo" },
      ],
      idOpcionCorrecta: "d",
      explicacion: "El ventrículo izquierdo tiene la pared más gruesa porque debe generar la presión suficiente para enviar sangre oxigenada a todo el organismo a través de la aorta.",
    },
    {
      id: "1-q3",
      idTema: "1",
      enunciado: "La circulación pulmonar conecta el corazón con los pulmones.",
      tipo: "verdadero-falso",
      dificultad: "facil",
      opciones: [
        { id: "v", etiqueta: "Verdadero" },
        { id: "f", etiqueta: "Falso" },
      ],
      idOpcionCorrecta: "v",
      explicacion: "La circulación pulmonar (o menor) transporta sangre entre el corazón y los pulmones para oxigenarla.",
    },
    {
      id: "1-q4",
      idTema: "1",
      enunciado: "¿Cuál de estos NO es un componente de la sangre?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "Plasma" },
        { id: "b", etiqueta: "Glóbulos rojos" },
        { id: "c", etiqueta: "Sinapsis" },
        { id: "d", etiqueta: "Plaquetas" },
      ],
      idOpcionCorrecta: "c",
      explicacion: "La sinapsis es un concepto del sistema nervioso, no un componente de la sangre. La sangre está formada por plasma, glóbulos rojos, glóbulos blancos y plaquetas.",
    },
    {
      id: "1-q5",
      idTema: "1",
      enunciado: "¿Qué célula sanguínea es responsable de transportar oxígeno?",
      tipo: "opcion-multiple",
      dificultad: "facil",
      opciones: [
        { id: "a", etiqueta: "Leucocitos" },
        { id: "b", etiqueta: "Plaquetas" },
        { id: "c", etiqueta: "Eritrocitos" },
        { id: "d", etiqueta: "Linfocitos" },
      ],
      idOpcionCorrecta: "c",
      explicacion: "Los eritrocitos (glóbulos rojos) contienen hemoglobina, proteína encargada de transportar el oxígeno por el cuerpo.",
    },
    {
      id: "1-q6",
      idTema: "1",
      enunciado: "Describe brevemente la diferencia entre sístole y diástole.",
      tipo: "abierta",
      dificultad: "dificil",
      textoRespuestaCorrecta:
        "La sístole es la fase de contracción del corazón, en la que expulsa sangre; la diástole es la fase de relajación, en la que se llena de sangre.",
      explicacion: "La alternancia entre sístole y diástole constituye el ciclo cardíaco completo.",
    },
    {
      id: "1-q7",
      idTema: "1",
      enunciado: "¿En qué vasos ocurre el intercambio de gases y nutrientes con los tejidos?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "Arterias" },
        { id: "b", etiqueta: "Venas" },
        { id: "c", etiqueta: "Capilares" },
        { id: "d", etiqueta: "Aorta" },
      ],
      idOpcionCorrecta: "c",
      explicacion: "Los capilares tienen paredes muy delgadas que permiten el intercambio directo de sustancias entre la sangre y los tejidos.",
    },
    {
      id: "1-q8",
      idTema: "1",
      enunciado: "Las venas siempre transportan sangre pobre en oxígeno.",
      tipo: "verdadero-falso",
      dificultad: "dificil",
      opciones: [
        { id: "v", etiqueta: "Verdadero" },
        { id: "f", etiqueta: "Falso" },
      ],
      idOpcionCorrecta: "f",
      explicacion: "Es falso: las venas pulmonares transportan sangre oxigenada desde los pulmones hacia la aurícula izquierda.",
    },
  ],
  "2": [
    {
      id: "2-q1",
      idTema: "2",
      enunciado: "¿Qué hecho simboliza el inicio de la Revolución Francesa?",
      tipo: "opcion-multiple",
      dificultad: "facil",
      opciones: [
        { id: "a", etiqueta: "La ejecución de Luis XVI" },
        { id: "b", etiqueta: "La toma de la Bastilla" },
        { id: "c", etiqueta: "El golpe de Napoleón" },
        { id: "d", etiqueta: "La Declaración de Independencia" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "El asalto a la Bastilla el 14 de julio de 1789 se convirtió en el símbolo del estallido revolucionario.",
    },
    {
      id: "2-q2",
      idTema: "2",
      enunciado: "¿Qué documento proclamó la libertad y la igualdad como derechos fundamentales en 1789?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "El Código Civil" },
        { id: "b", etiqueta: "La Constitución de 1791" },
        { id: "c", etiqueta: "La Declaración de los Derechos del Hombre" },
        { id: "d", etiqueta: "El Edicto de Nantes" },
      ],
      idOpcionCorrecta: "c",
      explicacion: "La Declaración de los Derechos del Hombre y del Ciudadano, de agosto de 1789, estableció principios de libertad, igualdad y soberanía nacional.",
    },
    {
      id: "2-q3",
      idTema: "2",
      enunciado: "El Terror fue liderado principalmente por Maximilien Robespierre.",
      tipo: "verdadero-falso",
      dificultad: "media",
      opciones: [
        { id: "v", etiqueta: "Verdadero" },
        { id: "f", etiqueta: "Falso" },
      ],
      idOpcionCorrecta: "v",
      explicacion: "Robespierre encabezó el Comité de Salvación Pública durante el período conocido como el Terror (1793-1794).",
    },
    {
      id: "2-q4",
      idTema: "2",
      enunciado: "¿Cómo llegó Napoleón Bonaparte al poder?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "Fue elegido por sufragio universal" },
        { id: "b", etiqueta: "Heredó el trono" },
        { id: "c", etiqueta: "Mediante el golpe de Estado del 18 de Brumario" },
        { id: "d", etiqueta: "Fue nombrado por Robespierre" },
      ],
      idOpcionCorrecta: "c",
      explicacion: "En 1799 Napoleón dio un golpe de Estado que puso fin al Directorio e inició el Consulado.",
    },
    {
      id: "2-q5",
      idTema: "2",
      enunciado: "¿Qué estamento social conformaba la mayoría de la población y no gozaba de privilegios fiscales?",
      tipo: "opcion-multiple",
      dificultad: "facil",
      opciones: [
        { id: "a", etiqueta: "El clero" },
        { id: "b", etiqueta: "La nobleza" },
        { id: "c", etiqueta: "El Tercer Estado" },
        { id: "d", etiqueta: "La corte real" },
      ],
      idOpcionCorrecta: "c",
      explicacion: "El Tercer Estado, compuesto por campesinos, burgueses y trabajadores urbanos, soportaba la mayor carga fiscal sin privilegios políticos.",
    },
    {
      id: "2-q6",
      idTema: "2",
      enunciado: "Explica brevemente una causa económica de la Revolución Francesa.",
      tipo: "abierta",
      dificultad: "dificil",
      textoRespuestaCorrecta:
        "La crisis financiera del Estado, agravada por guerras costosas y un sistema fiscal que exoneraba a la nobleza y el clero, fue una causa económica central.",
      explicacion: "El déficit fiscal y la desigualdad tributaria alimentaron el descontento social previo a 1789.",
    },
  ],
  "3": [
    {
      id: "3-q1",
      idTema: "3",
      enunciado: "¿Qué principio de la POO oculta los detalles internos de un objeto?",
      tipo: "opcion-multiple",
      dificultad: "facil",
      opciones: [
        { id: "a", etiqueta: "Herencia" },
        { id: "b", etiqueta: "Encapsulamiento" },
        { id: "c", etiqueta: "Polimorfismo" },
        { id: "d", etiqueta: "Abstracción" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "El encapsulamiento oculta el estado interno de un objeto y solo expone lo necesario mediante métodos públicos.",
    },
    {
      id: "3-q2",
      idTema: "3",
      enunciado: "¿Qué relación describe mejor la herencia entre clases?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "'tiene un'" },
        { id: "b", etiqueta: "'es un'" },
        { id: "c", etiqueta: "'usa un'" },
        { id: "d", etiqueta: "'depende de'" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "La herencia modela relaciones de tipo 'es un', por ejemplo: un 'Perro' es un 'Animal'.",
    },
    {
      id: "3-q3",
      idTema: "3",
      enunciado: "Una clase es lo mismo que un objeto.",
      tipo: "verdadero-falso",
      dificultad: "facil",
      opciones: [
        { id: "v", etiqueta: "Verdadero" },
        { id: "f", etiqueta: "Falso" },
      ],
      idOpcionCorrecta: "f",
      explicacion: "Una clase es la plantilla; un objeto es una instancia concreta creada a partir de esa clase.",
    },
    {
      id: "3-q4",
      idTema: "3",
      enunciado: "¿Qué forma de polimorfismo ocurre cuando una subclase redefine un método heredado?",
      tipo: "opcion-multiple",
      dificultad: "dificil",
      opciones: [
        { id: "a", etiqueta: "Sobrecarga" },
        { id: "b", etiqueta: "Sobrescritura" },
        { id: "c", etiqueta: "Encapsulamiento" },
        { id: "d", etiqueta: "Composición" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "La sobrescritura (override) permite que una subclase redefina el comportamiento de un método heredado de su superclase.",
    },
    {
      id: "3-q5",
      idTema: "3",
      enunciado: "¿Qué mecanismo permite definir un contrato sin implementar todo el comportamiento?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "Una interfaz o clase abstracta" },
        { id: "b", etiqueta: "Una variable estática" },
        { id: "c", etiqueta: "Un constructor" },
        { id: "d", etiqueta: "Un bucle for" },
      ],
      idOpcionCorrecta: "a",
      explicacion: "Las interfaces y clases abstractas permiten definir qué métodos debe tener una clase, sin obligar a implementarlos todos de inmediato.",
    },
    {
      id: "3-q6",
      idTema: "3",
      enunciado: "Explica con tus palabras qué es la abstracción en POO.",
      tipo: "abierta",
      dificultad: "dificil",
      textoRespuestaCorrecta:
        "La abstracción consiste en modelar los aspectos esenciales de un problema, ocultando los detalles de implementación irrelevantes para quien usa la clase.",
      explicacion: "La abstracción se centra en el 'qué hace' un objeto, no en el 'cómo lo hace' internamente.",
    },
  ],
  "4": [
    {
      id: "4-q1",
      idTema: "4",
      enunciado: "¿Qué representa geométricamente la derivada de una función en un punto?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "El área bajo la curva" },
        { id: "b", etiqueta: "La pendiente de la recta tangente" },
        { id: "c", etiqueta: "El valor máximo de la función" },
        { id: "d", etiqueta: "La distancia al eje x" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "La derivada en un punto equivale a la pendiente de la recta tangente a la curva en ese punto.",
    },
    {
      id: "4-q2",
      idTema: "4",
      enunciado: "¿Cuál es la derivada de x³?",
      tipo: "opcion-multiple",
      dificultad: "facil",
      opciones: [
        { id: "a", etiqueta: "3x" },
        { id: "b", etiqueta: "x²" },
        { id: "c", etiqueta: "3x²" },
        { id: "d", etiqueta: "3x³" },
      ],
      idOpcionCorrecta: "c",
      explicacion: "Aplicando la regla de la potencia: la derivada de xⁿ es n·xⁿ⁻¹, por lo que la derivada de x³ es 3x².",
    },
    {
      id: "4-q3",
      idTema: "4",
      enunciado: "Una función debe ser continua en un punto para poder ser derivable allí.",
      tipo: "verdadero-falso",
      dificultad: "media",
      opciones: [
        { id: "v", etiqueta: "Verdadero" },
        { id: "f", etiqueta: "Falso" },
      ],
      idOpcionCorrecta: "v",
      explicacion: "La continuidad es una condición necesaria (aunque no suficiente) para la derivabilidad en un punto.",
    },
    {
      id: "4-q4",
      idTema: "4",
      enunciado: "¿Qué regla se usa para derivar una función compuesta?",
      tipo: "opcion-multiple",
      dificultad: "dificil",
      opciones: [
        { id: "a", etiqueta: "Regla de la cadena" },
        { id: "b", etiqueta: "Regla del producto" },
        { id: "c", etiqueta: "Regla de L'Hôpital" },
        { id: "d", etiqueta: "Regla del cociente" },
      ],
      idOpcionCorrecta: "a",
      explicacion: "La regla de la cadena permite derivar funciones compuestas, multiplicando las derivadas de la función externa e interna.",
    },
    {
      id: "4-q5",
      idTema: "4",
      enunciado: "¿Qué indica un punto donde la derivada de una función se anula?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "Una discontinuidad" },
        { id: "b", etiqueta: "Un posible máximo o mínimo local" },
        { id: "c", etiqueta: "Una asíntota" },
        { id: "d", etiqueta: "Un punto de inflexión obligatorio" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "Los puntos críticos, donde f'(x) = 0, son candidatos a máximos o mínimos locales de la función.",
    },
  ],
  "5": [
    {
      id: "5-q1",
      idTema: "5",
      enunciado: "¿Qué partes componen el sistema nervioso central?",
      tipo: "opcion-multiple",
      dificultad: "facil",
      opciones: [
        { id: "a", etiqueta: "Encéfalo y médula espinal" },
        { id: "b", etiqueta: "Nervios craneales y espinales" },
        { id: "c", etiqueta: "Sistema simpático y parasimpático" },
        { id: "d", etiqueta: "Receptores sensoriales" },
      ],
      idOpcionCorrecta: "a",
      explicacion: "El sistema nervioso central está formado por el encéfalo y la médula espinal.",
    },
    {
      id: "5-q2",
      idTema: "5",
      enunciado: "¿Dónde ocurre la comunicación entre dos neuronas?",
      tipo: "opcion-multiple",
      dificultad: "media",
      opciones: [
        { id: "a", etiqueta: "En el núcleo celular" },
        { id: "b", etiqueta: "En la sinapsis" },
        { id: "c", etiqueta: "En el axón únicamente" },
        { id: "d", etiqueta: "En la médula ósea" },
      ],
      idOpcionCorrecta: "b",
      explicacion: "La sinapsis es el punto de contacto donde una neurona libera neurotransmisores que son captados por la siguiente.",
    },
    {
      id: "5-q3",
      idTema: "5",
      enunciado: "El sistema nervioso autónomo simpático prepara al cuerpo para el reposo y la digestión.",
      tipo: "verdadero-falso",
      dificultad: "media",
      opciones: [
        { id: "v", etiqueta: "Verdadero" },
        { id: "f", etiqueta: "Falso" },
      ],
      idOpcionCorrecta: "f",
      explicacion: "Es el sistema parasimpático el que favorece el reposo y la digestión; el simpático prepara al cuerpo para la acción ('lucha o huida').",
    },
    {
      id: "5-q4",
      idTema: "5",
      enunciado: "¿Qué es un arco reflejo?",
      tipo: "opcion-multiple",
      dificultad: "dificil",
      opciones: [
        { id: "a", etiqueta: "Una respuesta rápida e involuntaria mediada por la médula espinal" },
        { id: "b", etiqueta: "Un tipo de neurotransmisor" },
        { id: "c", etiqueta: "Una parte del encéfalo" },
        { id: "d", etiqueta: "Un tipo de sinapsis química" },
      ],
      idOpcionCorrecta: "a",
      explicacion: "El arco reflejo permite respuestas rápidas ante estímulos sin que la señal llegue necesariamente al encéfalo.",
    },
  ],
};

export function obtenerPreguntasDelTema(idTema: string): PreguntaEstudio[] {
  return [...(bancoPreguntas[idTema] ?? []), ...(bancoPreguntasExtra[idTema] ?? [])];
}
